name: nsf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  timeago: ^3.6.1
  intl: ^0.19.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0 
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
      - .env
      - assets/fonts/
      - assets/icons/
      - assets/background/
      # - assets/svg/
      # - assets/gif/
      # - assets/json/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf